In [5]:
import tensorflow as tf #딥러닝 라이브러리
import numpy as np # 다차원 배열 라이브러리
import matplotlib.pyplot as plt # 시각화 라이브러리
import sklearn #머신러닝 라이브러리
import seaborn as sns #시각화 고급 라이브러리
import pandas as pd # 데이터 분석 라이브러리


In [6]:
data = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

In [12]:
def createData_rnn(data_arr,time_step=4):# 20개(총갯수) 16번(반복회수) 반복
    x_data = [];y_data = []
    for i in range(len(data_arr)-time_step):
        x_data.append(data_arr[i:time_step+i])
        y_data.append(data_arr[time_step+i])
    return np.array(x_data),np.array(y_data).reshape(-1,1)
    

In [14]:
x_data,y_data = createData_rnn(data)
print(x_data.shape)
print(y_data.shape)
print(x_data[:2])
print(y_data[:2])
print(x_data[-2:])
print(y_data[-2:])

(16, 4)
(16, 1)
[[1 2 3 4]
 [2 3 4 5]]
[[5]
 [6]]
[[15 16 17 18]
 [16 17 18 19]]
[[19]
 [20]]


In [17]:
TIME_STEP = 4
from tensorflow.keras import Sequential, Input
from tensorflow.keras.layers import SimpleRNN
model = Sequential()
model.add(Input((TIME_STEP,)))
print(model(x_data)[:2])


tf.Tensor(
[[1. 2. 3. 4.]
 [2. 3. 4. 5.]], shape=(2, 4), dtype=float32)
